### ISSUE TITLE
How to control message with position(1:1)

### ISSUE THREAD

**Issue by chinesedfan** [unifiedjs/unified-message-control#4]
The current `check` [logic](https://github.com/unifiedjs/unified-message-control/blob/master/index.js#L225) requires the message position should be after the mark begin. It is reasonable in most cases.

But if a message belongs to the whole file, like [missing license](https://github.com/sindresorhus/awesome-lint/blob/master/rules/license.js#L15), we can't declare a mark more before than 1:1(line:column).

**Comment by wooorm** [comment]
So first of all, I believe [this message](https://github.com/sindresorhus/awesome-lint/blob/39411d9f1d6af6ae01e3963fe06bcd28eec4b089/rules/license.js#L20) should in fact be about `license`, not the whole tree?

Otherwise: I think it makes sense!

**Comment by chinesedfan** [comment]
@wooorm You referred to another line(#L20). My example is #L15. :)

**Comment by wooorm** [comment]
@chinesedfan Yeah I know, but I just saw it anyway and wanted to mention it ;)

**Comment by chinesedfan** [comment]
@wooorm OK, thanks for your finding and I will notify [sindresorhus/awesome-lint](https://github.com/sindresorhus/awesome-lint). Let's back to this issue. Should this package consider messages that belong to the whole file? If yes, how can we control them?

**Comment by wooorm** [comment]
> Should this package consider messages that belong to the whole file?

Yep, I think sosee my earlier comment: “I think it makes sense!”

> If yes, how can we control them?

It’s been a while since I’ve delved into this code! Maybe we can change https://github.com/unifiedjs/unified-message-control/blob/4d6f75ea6cbab1396e8c55a734837c3ec2b1c539/index.js#L131-L139. We’ll have to investigate how this affects the ecosystem tho 🤔
