### ISSUE TITLE
Types not throwing expected errors in TS4

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/unified-message-control#9]
### Subject of the issue

```
> unified-message-control@3.0.1 test-types /Users/tilde/Code/oss/unified-message-control
> dtslint

Error: /Users/tilde/Code/oss/unified-message-control/type-test.ts:82:3
ERROR: 82:3   expect  TypeScript@4.0 compile error: 
Type 'false' is not assignable to type 'true'.
ERROR: 84:1   expect  TypeScript@4.0: Expected an error on this line, but found none.
ERROR: 99:3   expect  TypeScript@4.0 compile error: 
Type 'true' is not assignable to type 'false | undefined'.
ERROR: 101:1  expect  TypeScript@4.0: Expected an error on this line, but found none.
ERROR: 174:3  expect  TypeScript@4.0 compile error: 
Type 'false' is not assignable to type 'true'.
ERROR: 176:1  expect  TypeScript@4.0: Expected an error on this line, but found none.
ERROR: 191:3  expect  TypeScript@4.0 compile error: 
Type 'true' is not assignable to type 'false | undefined'.
ERROR: 193:1  expect  TypeScript@4.0: Expected an error on this line, but found none.
```
### Steps to reproduce

`git clone`, `npm install`, `npm run test-types`

---

/cc @Zemnmez, @ChristianMurphy,

**Comment by ChristianMurphy** [comment]
@wooorm I'm not able to reproduce this issue locally.
This issue can stem from dtslint caching pre-release versions of typescript and not updating them as they get bug fixes.
Try running `rm -rf ~.dts` to clear the cached versions, then running `npm run test-types` again.

**Comment by wooorm** [comment]
🤔🤔 Just did that and it still happens.

**Comment by wooorm** [comment]
`~/.dts/typescript-installs/4.0/package.json` contains:

```
{"description":"Installs typescript@next","repository":"N/A","license":"MIT","dependencies":{"typescript":"next"}}
```

`next` to me sounds pretty error prone?

**Comment by wooorm** [comment]
[This project in Travis had the same errors btw, not just me](https://travis-ci.org/github/unifiedjs/unified-message-control/jobs/700564747). I’m guessing that it’s the latest TS version that breaks this, and that you have an older, working, version cached?

**Comment by ChristianMurphy** [comment]
`next` is a nightly, it is mostly stable.
The main difference between versions is where errors get reported, in this case it appears a recent 4.0 version moved the error from `enable` to to `reset` causing the test to fail, #10 resolves this by putting both on the same line to catch both.
